'use client';

import Link from 'next/link';
import { BottomNavigation } from '@/components/BottomNavigation';
import { Header } from '@/components/Header';
import { AuthProvider } from '@/lib/context/AuthContext';
import { useSearchParams } from 'next/navigation';
import { MapPin, Phone, Mail, ArrowLeft } from 'lucide-react';
import { useState, useEffect } from 'react';
import { useGoogleGeocoding } from '@/lib/hooks/useGoogleMaps';

export default function SearchViewPage() {
  return (
    <AuthProvider>
      <SearchViewPageContent />
    </AuthProvider>
  );
}

function SearchViewPageContent() {
  const searchParams = useSearchParams();
  const address = searchParams.get('address') || '123 Mountain View Road, Telluride, CO 81435';
  const [streetViewUrl, setStreetViewUrl] = useState('');
  const [location, setLocation] = useState<{ lat: number; lng: number } | null>(null);
  const geocoding = useGoogleGeocoding();

  // Geocode the address to get coordinates for Street View
  useEffect(() => {
    const initializeStreetView = async () => {
      try {
        const result = await geocoding.geocode(address);
        if (result && result.location) {
          setLocation(result.location);
          
          // Create Google Street View API URL with real coordinates
          const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;
          const streetViewUrl = `https://maps.googleapis.com/maps/api/streetview?size=600x400&location=${result.location.lat},${result.location.lng}&key=${apiKey}`;
          setStreetViewUrl(streetViewUrl);
        }
      } catch (error) {
        console.error('Failed to geocode address:', error);
      }
    };

    if (address) {
      initializeStreetView();
    }
  }, [address, geocoding]);

  return (
    <main className="pb-24">
      <Header />
      <div className="px-4 py-8 max-w-4xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <Link
          href="/search"
          className="flex items-center gap-2 text-orange-500 hover:text-orange-600 mb-4"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Search
        </Link>
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Parcel Details</h1>
        <p className="text-gray-600 flex items-center gap-2">
          <MapPin className="w-4 h-4" />
          {address}
        </p>
      </div>

      {/* Two Column Layout */}
      <div className="grid md:grid-cols-3 gap-8 mb-8">
        {/* Street View Section */}
        <div className="md:col-span-2">
          <div className="bg-gray-200 rounded-lg overflow-hidden h-96 mb-6 relative">
            {streetViewUrl ? (
              <iframe
                src={streetViewUrl}
'use client';

import { useState } from 'react';
import { Download, Share2, MapPin, Phone, Mail } from 'lucide-react';
import { useSearchParams } from 'next/navigation';

export default function SearchViewPage() {
  const searchParams = useSearchParams();
  const address = searchParams.get('address') || 'Property Address';
  const [shareMessage, setShareMessage] = useState('');

  const handleDownload = () => {
    const content = `Property Search Result
========================

Address: ${address}
Phone: (970) 555-0123
Email: contact@geoselect.com

Property Overview:
- Status: Active
- Details: [Property information will be populated here]

Generated by GeoSelect
${new Date().toLocaleDateString()}`;

    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `property-${address.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleShare = async () => {
    const shareText = `Check out this property search result: ${address}`;
    const shareUrl = `${window.location.origin}/search/view?address=${encodeURIComponent(address)}`;
    try {
      await navigator.clipboard.writeText(`${shareText}\n${shareUrl}`);
      setShareMessage('Copied to clipboard!');
      setTimeout(() => setShareMessage(''), 3000);
    } catch (err) {
      setShareMessage('Failed to copy');
      setTimeout(() => setShareMessage(''), 3000);
    }
  };

  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      {/* Header */}
      <div className="sticky top-0 z-40 bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <MapPin className="w-6 h-6 text-orange-500" />
              <h1 className="text-xl sm:text-2xl font-bold text-gray-900 dark:text-white">
                {address}
              </h1>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                className="flex items-center gap-2 px-3 sm:px-4 py-2 rounded-lg bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-900 dark:text-white font-medium transition-colors"
              >
                <Download className="w-4 h-4" />
                <span className="hidden sm:inline">Download</span>
              </button>
              <div className="relative">
                <button
                  onClick={handleShare}
                  className="flex items-center gap-2 px-3 sm:px-4 py-2 rounded-lg bg-orange-500 hover:bg-orange-600 text-white font-medium transition-colors"
                >
                  <Share2 className="w-4 h-4" />
                  <span className="hidden sm:inline">Share</span>
                </button>
                {shareMessage && (
                  <div className="absolute top-full right-0 mt-2 bg-gray-900 dark:bg-gray-100 text-white dark:text-gray-900 px-3 py-2 rounded text-sm whitespace-nowrap">
                    {shareMessage}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Property Overview */}
        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-6 mb-8">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
            Property Overview
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            <div>
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Address</p>
              <p className="font-medium text-gray-900 dark:text-white">{address}</p>
            </div>
            <div>
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Status</p>
              <p className="font-medium text-green-600 dark:text-green-400">Active</p>
            </div>
            <div>
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Contact</p>
              <div className="flex items-center gap-2">
                <Phone className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <p className="font-medium text-gray-900 dark:text-white">(970) 555-0123</p>
              </div>
            </div>
            <div>
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">Email</p>
              <div className="flex items-center gap-2">
                <Mail className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <p className="font-medium text-gray-900 dark:text-white">contact@geoselect.com</p>
              </div>
            </div>
          </div>
        </div>

        {/* Map View Placeholder */}
        <div className="bg-gray-100 dark:bg-gray-700 rounded-lg border border-gray-200 dark:border-gray-600 overflow-hidden mb-8">
          <div className="h-96 flex items-center justify-center">
            <p className="text-gray-500 dark:text-gray-400">Map view will be displayed here</p>
          </div>
        </div>

        {/* Property Details Placeholder */}
        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-6">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
            Property Details
          </h2>
          <div className="space-y-4">
            <p className="text-gray-600 dark:text-gray-400">
              Detailed property information will be populated here based on your search results.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function SearchViewPage() {
  const searchParams = useSearchParams();
  const address = searchParams.get('address') || 'Unknown Address';
  const [shareMessage, setShareMessage] = useState('');

  const handleDownload = () => {
    const content = `Search Result for: ${address}
Generated: ${new Date().toLocaleString()}

Address: ${address}
Status: Property information pending

---
Downloaded from GeoSelect`;

    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `property-${address.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleShare = async () => {
    const shareText = `Check out this property search result: ${address}`;
    const shareUrl = `${window.location.origin}/search/view?address=${encodeURIComponent(address)}`;

    try {
      await navigator.clipboard.writeText(`${shareText}\n${shareUrl}`);
      setShareMessage('Copied to clipboard!');
      setTimeout(() => setShareMessage(''), 3000);
    } catch (err) {
      console.error('Failed to copy:', err);
      setShareMessage('Failed to copy');
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between gap-4 flex-wrap">
            <div className="flex items-center gap-2 min-w-0 flex-1">
              <MapPin className="h-5 w-5 text-orange-600 flex-shrink-0" />
              <h1 className="text-lg sm:text-2xl font-bold text-gray-900 dark:text-white truncate">
                {address}
              </h1>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handleDownload}
                className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-200 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors duration-200 shadow-sm"
                title="Download property information"
              >
                <Download className="h-5 w-5" />
                <span className="hidden sm:inline text-sm font-medium">Download</span>
              </button>

              <div className="relative">
                <button
                  onClick={handleShare}
                  className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 transition-colors duration-200 shadow-sm"
                  title="Share this property"
                >
                  <Share2 className="h-5 w-5" />
                  <span className="hidden sm:inline text-sm font-medium">Share</span>
                </button>

                {shareMessage && (
                  <div className="absolute top-full right-0 mt-2 px-3 py-2 bg-green-600 text-white rounded-lg text-sm whitespace-nowrap shadow-lg z-20">
                    {shareMessage}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Property Overview
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="flex gap-3">
              <MapPin className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Address</p>
                <p className="font-medium text-gray-900 dark:text-white">{address}</p>
              </div>
            </div>

            <div className="flex gap-3">
              <Phone className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Contact</p>
                <p className="font-medium text-gray-900 dark:text-white">Pending</p>
              </div>
            </div>

            <div className="flex gap-3">
              <Mail className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Status</p>
                <p className="font-medium text-gray-900 dark:text-white">Data Loading</p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Map View
          </h2>
          <div className="w-full h-96 bg-gray-200 dark:bg-gray-700 rounded-lg flex items-center justify-center">
            <p className="text-gray-500 dark:text-gray-400">Map integration pending</p>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Property Details
          </h2>
          <p className="text-gray-600 dark:text-gray-400">
            Detailed property information will appear here once the search is complete.
          </p>
        </div>
      </div>
    </div>
  );
}

import { useState } from 'react';
import { Download, Share2, MapPin, Phone, Mail } from 'lucide-react';
import { useSearchParams } from 'next/navigation';

export default function SearchViewPage() {
  const searchParams = useSearchParams();
  const address = searchParams.get('address') || 'Unknown Address';
  const [shareMessage, setShareMessage] = useState('');

  const handleDownload = () => {
    const content = `Search Result for: ${address}
Generated: ${new Date().toLocaleString()}

Address: ${address}
Status: Property information pending

---
Downloaded from GeoSelect`;

    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `property-${address.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleShare = async () => {
    const shareText = `Check out this property search result: ${address}`;
    const shareUrl = `${window.location.origin}/search/view?address=${encodeURIComponent(address)}`;

    try {
      await navigator.clipboard.writeText(`${shareText}\n${shareUrl}`);
      setShareMessage('Copied to clipboard!');
      setTimeout(() => setShareMessage(''), 3000);
    } catch (err) {
      console.error('Failed to copy:', err);
      setShareMessage('Failed to copy');
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between gap-4 flex-wrap">
            <div className="flex items-center gap-2 min-w-0 flex-1">
              <MapPin className="h-5 w-5 text-orange-600 flex-shrink-0" />
              <h1 className="text-lg sm:text-2xl font-bold text-gray-900 dark:text-white truncate">
                {address}
              </h1>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handleDownload}
                className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-200 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors duration-200 shadow-sm"
                title="Download property information"
              >
                <Download className="h-5 w-5" />
                <span className="hidden sm:inline text-sm font-medium">Download</span>
              </button>

              <div className="relative">
                <button
                  onClick={handleShare}
                  className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 transition-colors duration-200 shadow-sm"
                  title="Share this property"
                >
                  <Share2 className="h-5 w-5" />
                  <span className="hidden sm:inline text-sm font-medium">Share</span>
                </button>

                {shareMessage && (
                  <div className="absolute top-full right-0 mt-2 px-3 py-2 bg-green-600 text-white rounded-lg text-sm whitespace-nowrap shadow-lg z-20">
                    {shareMessage}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Property Overview
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="flex gap-3">
              <MapPin className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Address</p>
                <p className="font-medium text-gray-900 dark:text-white">{address}</p>
              </div>
            </div>

            <div className="flex gap-3">
              <Phone className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Contact</p>
                <p className="font-medium text-gray-900 dark:text-white">Pending</p>
              </div>
            </div>

            <div className="flex gap-3">
              <Mail className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Status</p>
                <p className="font-medium text-gray-900 dark:text-white">Data Loading</p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Map View
          </h2>
          <div className="w-full h-96 bg-gray-200 dark:bg-gray-700 rounded-lg flex items-center justify-center">
            <p className="text-gray-500 dark:text-gray-400">Map integration pending</p>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Property Details
          </h2>
          <p className="text-gray-600 dark:text-gray-400">
            Detailed property information will appear here once the search is complete.
          </p>
        </div>
      </div>
    </div>
  );
}

import { useState } from 'react';
import { Download, Share2, MapPin, Phone, Mail } from 'lucide-react';
import { useSearchParams } from 'next/navigation';

export default function SearchViewPage() {
  const searchParams = useSearchParams();
  const address = searchParams.get('address') || 'Unknown Address';
  const [shareMessage, setShareMessage] = useState('');

  const handleDownload = () => {
    const content = `Search Result for: ${address}
Generated: ${new Date().toLocaleString()}

Address: ${address}
Status: Property information pending

---
Downloaded from GeoSelect`;

    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `property-${address.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleShare = async () => {
    const shareText = `Check out this property search result: ${address}`;
    const shareUrl = `${window.location.origin}/search/view?address=${encodeURIComponent(address)}`;

    try {
      await navigator.clipboard.writeText(`${shareText}\n${shareUrl}`);
      setShareMessage('Copied to clipboard!');
      setTimeout(() => setShareMessage(''), 3000);
    } catch (err) {
      console.error('Failed to copy:', err);
      setShareMessage('Failed to copy');
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between gap-4 flex-wrap">
            <div className="flex items-center gap-2 min-w-0 flex-1">
              <MapPin className="h-5 w-5 text-orange-600 flex-shrink-0" />
              <h1 className="text-lg sm:text-2xl font-bold text-gray-900 dark:text-white truncate">
                {address}
              </h1>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handleDownload}
                className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-200 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors duration-200 shadow-sm"
                title="Download property information"
              >
                <Download className="h-5 w-5" />
                <span className="hidden sm:inline text-sm font-medium">Download</span>
              </button>

              <div className="relative">
                <button
                  onClick={handleShare}
                  className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 transition-colors duration-200 shadow-sm"
                  title="Share this property"
                >
                  <Share2 className="h-5 w-5" />
                  <span className="hidden sm:inline text-sm font-medium">Share</span>
                </button>

                {shareMessage && (
                  <div className="absolute top-full right-0 mt-2 px-3 py-2 bg-green-600 text-white rounded-lg text-sm whitespace-nowrap shadow-lg z-20">
                    {shareMessage}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Property Overview
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="flex gap-3">
              <MapPin className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Address</p>
                <p className="font-medium text-gray-900 dark:text-white">{address}</p>
              </div>
            </div>

            <div className="flex gap-3">
              <Phone className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Contact</p>
                <p className="font-medium text-gray-900 dark:text-white">Pending</p>
              </div>
            </div>

            <div className="flex gap-3">
              <Mail className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Status</p>
                <p className="font-medium text-gray-900 dark:text-white">Data Loading</p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Map View
          </h2>
          <div className="w-full h-96 bg-gray-200 dark:bg-gray-700 rounded-lg flex items-center justify-center">
            <p className="text-gray-500 dark:text-gray-400">Map integration pending</p>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Property Details
          </h2>
          <p className="text-gray-600 dark:text-gray-400">
            Detailed property information will appear here once the search is complete.
          </p>
        </div>
      </div>
    </div>
  );
}

import { useState } from 'react';
import { Download, Share2, MapPin, Phone, Mail } from 'lucide-react';
import { useSearchParams } from 'next/navigation';

export default function SearchViewPage() {
  const searchParams = useSearchParams();
  const address = searchParams.get('address') || 'Unknown Address';
  const [shareMessage, setShareMessage] = useState('');

  const handleDownload = () => {
    const content = `Search Result for: ${address}
Generated: ${new Date().toLocaleString()}

Address: ${address}
Status: Property information pending

---
Downloaded from GeoSelect`;

    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `property-${address.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleShare = async () => {
    const shareText = `Check out this property search result: ${address}`;
    const shareUrl = `${window.location.origin}/search/view?address=${encodeURIComponent(address)}`;

    try {
      await navigator.clipboard.writeText(`${shareText}\n${shareUrl}`);
      setShareMessage('Copied to clipboard!');
      setTimeout(() => setShareMessage(''), 3000);
    } catch (err) {
      console.error('Failed to copy:', err);
      setShareMessage('Failed to copy');
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between gap-4 flex-wrap">
            <div className="flex items-center gap-2 min-w-0 flex-1">
              <MapPin className="h-5 w-5 text-orange-600 flex-shrink-0" />
              <h1 className="text-lg sm:text-2xl font-bold text-gray-900 dark:text-white truncate">
                {address}
              </h1>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handleDownload}
                className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-200 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors duration-200 shadow-sm"
                title="Download property information"
              >
                <Download className="h-5 w-5" />
                <span className="hidden sm:inline text-sm font-medium">Download</span>
              </button>

              <div className="relative">
                <button
                  onClick={handleShare}
                  className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 transition-colors duration-200 shadow-sm"
                  title="Share this property"
                >
                  <Share2 className="h-5 w-5" />
                  <span className="hidden sm:inline text-sm font-medium">Share</span>
                </button>

                {shareMessage && (
                  <div className="absolute top-full right-0 mt-2 px-3 py-2 bg-green-600 text-white rounded-lg text-sm whitespace-nowrap shadow-lg z-20">
                    {shareMessage}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Property Overview
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="flex gap-3">
              <MapPin className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Address</p>
                <p className="font-medium text-gray-900 dark:text-white">{address}</p>
              </div>
            </div>

            <div className="flex gap-3">
              <Phone className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Contact</p>
                <p className="font-medium text-gray-900 dark:text-white">Pending</p>
              </div>
            </div>

            <div className="flex gap-3">
              <Mail className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Status</p>
                <p className="font-medium text-gray-900 dark:text-white">Data Loading</p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Map View
          </h2>
          <div className="w-full h-96 bg-gray-200 dark:bg-gray-700 rounded-lg flex items-center justify-center">
            <p className="text-gray-500 dark:text-gray-400">Map integration pending</p>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Property Details
          </h2>
          <p className="text-gray-600 dark:text-gray-400">
            Detailed property information will appear here once the search is complete.
          </p>
        </div>
      </div>
    </div>
  );
}

import { useState } from 'react';
import { Download, Share2, MapPin, Phone, Mail } from 'lucide-react';
import { useSearchParams } from 'next/navigation';

export default function SearchViewPage() {
  const searchParams = useSearchParams();
  const address = searchParams.get('address') || 'Unknown Address';
  const [shareMessage, setShareMessage] = useState('');

  const handleDownload = () => {
    const content = `Search Result for: ${address}
Generated: ${new Date().toLocaleString()}

Address: ${address}
Status: Property information pending

---
Downloaded from GeoSelect`;

    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `property-${address.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleShare = async () => {
    const shareText = `Check out this property search result: ${address}`;
    const shareUrl = `${window.location.origin}/search/view?address=${encodeURIComponent(address)}`;

    try {
      await navigator.clipboard.writeText(`${shareText}\n${shareUrl}`);
      setShareMessage('Copied to clipboard!');
      setTimeout(() => setShareMessage(''), 3000);
    } catch (err) {
      console.error('Failed to copy:', err);
      setShareMessage('Failed to copy');
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between gap-4 flex-wrap">
            <div className="flex items-center gap-2 min-w-0 flex-1">
              <MapPin className="h-5 w-5 text-orange-600 flex-shrink-0" />
              <h1 className="text-lg sm:text-2xl font-bold text-gray-900 dark:text-white truncate">
                {address}
              </h1>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handleDownload}
                className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-200 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors duration-200 shadow-sm"
                title="Download property information"
              >
                <Download className="h-5 w-5" />
                <span className="hidden sm:inline text-sm font-medium">Download</span>
              </button>

              <div className="relative">
                <button
                  onClick={handleShare}
                  className="inline-flex items-center gap-2 px-3 sm:px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 transition-colors duration-200 shadow-sm"
                  title="Share this property"
                >
                  <Share2 className="h-5 w-5" />
                  <span className="hidden sm:inline text-sm font-medium">Share</span>
                </button>

                {shareMessage && (
                  <div className="absolute top-full right-0 mt-2 px-3 py-2 bg-green-600 text-white rounded-lg text-sm whitespace-nowrap shadow-lg z-20">
                    {shareMessage}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Property Overview
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="flex gap-3">
              <MapPin className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Address</p>
                <p className="font-medium text-gray-900 dark:text-white">{address}</p>
              </div>
            </div>

            <div className="flex gap-3">
              <Phone className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Contact</p>
                <p className="font-medium text-gray-900 dark:text-white">Pending</p>
              </div>
            </div>

            <div className="flex gap-3">
              <Mail className="h-5 w-5 text-gray-400 flex-shrink-0 mt-1" />
              <div>
                <p className="text-sm text-gray-600 dark:text-gray-400">Status</p>
                <p className="font-medium text-gray-900 dark:text-white">Data Loading</p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mb-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Map View
          </h2>
          <div className="w-full h-96 bg-gray-200 dark:bg-gray-700 rounded-lg flex items-center justify-center">
            <p className="text-gray-500 dark:text-gray-400">Map integration pending</p>
          </div>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            Property Details
          </h2>
          <p className="text-gray-600 dark:text-gray-400">
            Detailed property information will appear here once the search is complete.
          </p>
        </div>
      </div>
    </div>
  );
}
              <div className="w-full h-full bg-gradient-to-br from-blue-400 to-blue-600 flex flex-col items-center justify-center text-white">
                <div className="animate-spin mb-4">📍</div>
                <h3 className="text-xl font-semibold mb-2">Loading Map...</h3>
                <p className="text-blue-100 text-center max-w-xs">
                  Getting location data for {address}
                </p>
              </div>
            )}
          </div>

          {/* Location Info */}
          {location && (
            <div className="bg-white border border-gray-200 rounded-lg p-4 mb-6">
              <p className="text-sm text-gray-600 mb-2">Coordinates</p>
              <p className="font-mono text-gray-900">
                {location.lat.toFixed(6)}, {location.lng.toFixed(6)}
              </p>
            </div>
          )}

          {/* Geocoding Error */}
          {geocoding.error && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-6">
              <p className="text-red-600 text-sm font-medium">Error loading map</p>
              <p className="text-red-500 text-sm">{geocoding.error}</p>
              <p className="text-red-500 text-xs mt-2">
                Check your Google Maps API key configuration in .env.local
              </p>
            </div>
          )}
        </div>

        {/* Summary Section */}
        <div className="space-y-6">
          {/* Property Info */}
          <div className="bg-white border border-gray-200 rounded-lg p-6">
            <h3 className="font-semibold text-gray-900 mb-4">Property Information</h3>
            <div className="space-y-4">
              <div>
                <p className="text-xs text-gray-500 uppercase font-semibold">Latitude</p>
                <p className="text-gray-800 font-medium">37.9377°</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 uppercase font-semibold">Longitude</p>
                <p className="text-gray-800 font-medium">-106.9167°</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 uppercase font-semibold">Area</p>
                <p className="text-gray-800 font-medium">15.5 acres</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 uppercase font-semibold">Zoning</p>
                <p className="text-gray-800 font-medium">Residential - Mountain</p>
              </div>
            </div>
          </div>

          {/* Contact Card */}
          <div className="bg-orange-50 border border-orange-200 rounded-lg p-6">
            <h3 className="font-semibold text-gray-900 mb-4">Need More Info?</h3>
            <div className="space-y-3">
              <a
                href="tel:+1-970-555-0100"
                className="flex items-center gap-3 text-orange-600 hover:text-orange-700 font-medium"
              >
                <Phone className="w-4 h-4" />
                +1 (970) 555-0100
              </a>
              <a
                href="mailto:info@geoselect.com"
                className="flex items-center gap-3 text-orange-600 hover:text-orange-700 font-medium"
              >
                <Mail className="w-4 h-4" />
                info@geoselect.com
              </a>
            </div>
          </div>

          {/* Sign Up CTA */}
          <Link
            href="/workspaces/create"
            className="block w-full px-4 py-3 bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition-colors font-semibold text-center"
          >
            Sign Up for More Features
          </Link>

          {/* Features List */}
          <div className="bg-gray-50 rounded-lg p-4">
            <p className="text-xs text-gray-600 font-semibold mb-3">UNLOCK WITH ACCOUNT:</p>
            <ul className="space-y-2 text-xs text-gray-700">
              <li>✓ Property analysis</li>
              <li>✓ Batch exports</li>
              <li>✓ AI insights</li>
              <li>✓ Historical data</li>
              <li>✓ Market comparisons</li>
            </ul>
          </div>
        </div>
      </div>

      {/* Map Section */}
      <div className="bg-white border border-gray-200 rounded-lg p-6 mb-8">
        <h3 className="font-semibold text-gray-900 mb-4">Map Location</h3>
        <div className="w-full h-64 bg-gray-100 rounded-lg flex items-center justify-center">
          <div className="text-center">
            <div className="text-5xl mb-3">🗺️</div>
            <p className="text-gray-600">Google Maps embedded view</p>
            <p className="text-gray-500 text-sm mt-1">37.9377°, -106.9167°</p>
          </div>
        </div>
      </div>

      <BottomNavigation />
      </div>
    </main>
  );
}
