// app/shared/[token]/page.tsx
import { notFound, redirect } from 'next/navigation';
import { validateShareLink, trackShareLinkView } from '@/lib/db/helpers/share-links';
import { getSnapshotRules, getSnapshotGaps } from '@/lib/db/helpers/provenance';
import { headers } from 'next/headers';

export default async function SharedReportPage({ params }: { params: { token: string } }) {
  const headersList = headers();
  const ipAddress = headersList.get('x-forwarded-for') || headersList.get('x-real-ip');
  const userAgent = headersList.get('user-agent');

  // Validate share link
  const validation = await validateShareLink(params.token);

  if (!validation.valid) {
    if (validation.reason === 'expired') {
      return <div>This share link has expired.</div>;
    }
    if (validation.reason === 'revoked') {
      return <div>This share link has been revoked.</div>;
    }
    if (validation.reason === 'auth_required') {
      redirect(`/login?return_to=/shared/${params.token}`);
    }
    notFound();
  }

  const shareLink = validation.shareLink!;

  // Track view
  await trackShareLinkView(
    shareLink.id,
    undefined, // userId if authenticated
    ipAddress || undefined,
    userAgent || undefined
  );

  // Fetch snapshot data
  const [rules, gaps] = await Promise.all([
    getSnapshotRules(shareLink.snapshot_id),
    getSnapshotGaps(shareLink.snapshot_id),
  ]);

  return (
    <div className="container max-w-4xl py-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">Parcel Report</h1>
        <p className="text-muted-foreground">
          Shared by {shareLink.recipient_email || 'GeoSelect'}
        </p>
      </div>

      {/* Render report with rules and gaps */}
      <div className="space-y-6">
        {/* Rules Section */}
        <div>
          <h2 className="text-2xl font-semibold mb-4">Rules & Constraints</h2>
          {rules.map((rule: any) => (
            <div key={rule.id} className="p-4 border rounded-lg mb-4">
              <h3 className="font-medium">{rule.rule_type}</h3>
              <p className="text-sm text-muted-foreground">{rule.description}</p>
              
              {/* Sources */}
              {rule.snapshot_sources && rule.snapshot_sources.length > 0 && (
                <div className="mt-2">
                  <p className="text-xs font-medium">Sources:</p>
                  {rule.snapshot_sources.map((source: any) => (
                    <div key={source.id} className="text-xs text-muted-foreground">
                      {source.name} - {source.citation}
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Gaps Section */}
        {gaps.length > 0 && (
          <div>
            <h2 className="text-2xl font-semibold mb-4">Data Gaps</h2>
            {gaps.map((gap: any) => (
              <div key={gap.id} className="p-4 border rounded-lg mb-4 border-yellow-500">
                <p className="text-sm">{gap.description}</p>
                <span className="text-xs text-muted-foreground capitalize">
                  {gap.gap_type} - {gap.severity}
                </span>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="mt-8 pt-8 border-t text-center text-sm text-muted-foreground">
        <p>This report was generated by GeoSelect</p>
        <p>View-only access • Do not redistribute</p>
      </div>
    </div>
  );
}
